
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # O la rama que uses

pool:
  name: 'Default'  # Para build inicial, luego cambiarás por tu agente


variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # o la versión que uses

- script: npm install
  displayName: 'Instalar dependencias'

- script: npm install typescript --save-dev
  displayName: 'Instalar TypeScript'

- script: npx playwright install
  displayName: 'Instalar Playwright'

- script: npm run build
  displayName: 'Compilar TypeScript'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'playwright-report/**/*.xml'
    testRunTitle: 'Playwright Tests'
    failTaskOnFailedTests: false
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'